# Generated by Django 5.0.4 on 2024-04-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(unique=True)),
                ('title', models.TextField(unique=True)),
                ('year', models.IntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField(default='None')),
                ('genres', models.TextField(default='None')),
                ('average_rating', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('authors', models.TextField(default='Jane Doe')),
            ],
        ),
    ]
