# Generated by Django 5.0.4 on 2024-04-30 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrec',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookrec',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
